[build]
# Pas de build Flutter sur Netlify
command = ""              # ou "echo skip"
publish = "."             # dossier à publier (tu as index.html/checkin.html à la racine)

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# (optionnel) redirection SPA si tu as un index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
